framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    http_client:
        scoped_clients:
            httpc:
                base_uri: https://api.thecatapi.com

    rate_limiter:
        login_attempts:
            policy: 'token_bucket'
            limit: 5
            rate: { interval: '1 minute', amount: 5 }

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

    form:
        csrf_protection:
            enabled: true
            field_name: 'custom_token_name'
